# Generated by Django 4.2.7 on 2024-09-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Scanned')),
            ],
        ),
    ]
